server:
  port: 5001
  servlet.context-path: /credit-line

springdoc:
  api-docs:
    path: /api-docs

  swagger-ui:
    path: /swagger

logging:
  level:
    root: INFO

ratio:
  cash-balance: 3
  monthly-revenue: 5