version: '3.7'
services:
  postgres:
    image: postgres:latest
    container_name: credit_line_postgres
    restart: "unless-stopped"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5432:5432'
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data
  redis:
    image: redis:latest
    container_name: credit_line_redis
    restart: "unless-stopped"
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/var/lib/postgresql/data

volumes:
  postgresql:
  postgresql_data:
  redis_data:
